### ISSUE TITLE
Unable to Install via Ansible-Galaxy requirements.txt

### ISSUE THREAD

**Issue by jpartain89** [don-rumata/ansible-role-install-virtualbox#1]
When trying to automatically install your role, the following error message due to the first published release being named different from your others. 

`[WARNING]: - don_rumata.ansible_role_install_virtualbox was NOT installed successfully: Unable to compare role versions (0.0.16,
v1.0.0, v1.0.1) to determine the most recent version due to incompatible version formats. Please contact the role author to resolve
versioning conflicts, or specify an explicit role version to install.`

**Comment by don-rumata** [comment]
As a temporary solution, use: `ansible-galaxy install don_rumata.ansible_role_install_virtualbox,v1.0.1`

**Comment by don-rumata** [comment]
Fixed
